name: 构建和部署
on: # 监听 main 分支上的 push 事件
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: 安装依赖
        run: pnpm install

      - name: 打包项目
        run: pnpm run build

      # 移除 Jekyll 相关步骤，添加目录验证
      - name: 验证构建结果
        run: |
          ls -la
          ls -la dist/

  deploy:
    needs: build
    runs-on:
      ubuntu-latest
      # 使用新版 GitHub Pages 部署方式
    steps:
      - name: 部署到 GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          target-branch: main
          build-directory: dist # 与 Vue 项目的输出目录一致
